# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/YUVRAJSINGH2804/2a9f0f3f0b9a00ad663db99df6dc2c2f/untitled0.ipynb
"""

import matplotlib.pyplot as plt

import numpy as np

# x=np.linspace(0,10,100)#gives 100 values equally space in 0 to 10
# y=np.sin(x)
# z=np.cos(x)

# print(x)
# print(y)


# sin wave

# plt.plot(x,y)
# plt.show()

#  cosine wave


# plt.plot(x,z)
# plt.show()

# adding title x-axis and y- axis labels

# plt.plot(x,y)
# plt.xlabel('angle')
# plt.ylabel('sine value')
# plt.title('sine wave')
# plt.show()

# parabole

# x=np.linspace(-10,10,20)
# y=x**2
# plt.show(x,y)

# plot parabola in red color with + symbol(r+)
# plot parabola in green color with + symbol(g+)
# plt.plot(x,y,'r+')
# plt.show()

# give two curve in same graph
x=np.linspace(-5,5,50)
plt.plot(x,np.sin(x),'g-')
plt.plot(x,np.cos(x),'r--')
plt.show()

#BAR PLOT
fig= plt.figure()
ax= fig.add_axes([0,0,1,1])
language=['english',"latin","french",'spanish','german']
people=[100,40,80,60,30]
ax.bar(language,people)
plt.xlabel('LANGUAGES')
plt.ylabel('NUMBER OF PEOPLE')
plt.show()

#for a pie chart

fig= plt.figure()
ax= fig.add_axes([0,0,1,1])
language=['english',"latin","french",'spanish','german']
people=[100,40,80,60,30]

ax.pie(people,labels=language,autopct='%1.1f%%')
plt.show()

#scatter plot

x=np.linspace(0,10,30)
y=np.sin(x)
z=np.cos(x)

fig2=plt.figure()
ax=fig2.add_axes([0,0,1,1])
ax.scatter(x,y,color='g')
ax.scatter(x,z,color='b')
plt.show()

#3d scatter plot
fig3=plt.figure()
ax= plt.axes(projection='3d')
z=20 * np.random.random(100)
x=np.sin(z)
y=np.cos(z)

ax.scatter(x,y,z,c=z,cmap='Blues')
plt.show()